### PR TITLE
Set nounset on Bash scripts (fixes #860)

### LINKED ISSUE #860: [Proposal] Set -x and -e, -u on each Bash script
Feature description
---------
Proposal 1: `set -x` on each Bash script to see every command which run.

Proposal 2: `set -e` and `set -u` on each Bash script to fail script if some script's command failed.

### PR DESCRIPTION
**Pull request by kuraga**
Trying to fix #860 in wider manner.

Check need...

### CODE REVIEW

File: tools/prod-django.sh [hunk 1]
```diff
@@ -2,6 +2,14 @@
 
 set -o errexit
 
+if [[ -z "${ADMIN_USERNAME}" ]]; then echo "Missing ADMIN_USERNAME environment variable" >&2; exit 1; fi
+if [[ -z "${ADMIN_PASSWORD}" ]]; then echo "Missing ADMIN_PASSWORD environment variable" >&2; exit 1; fi
+if [[ -z "${ADMIN_EMAIL}" ]]; then echo "Missing ADMIN_EMAIL environment variable" >&2; exit 1; fi
+if [[ -z "${PORT}" ]]; then echo "Missing PORT environment variable" >&2; exit 1; fi
+if [[ -z "${WORKERS}" ]]; then echo "Missing WORKERS environment variable" >&2; exit 1; fi
```
Comment (Hironsan) [inline tools/prod-django.sh:9]: This causes the failure of `docker-compose.prod.yml`. Because `PORT` and `WORKERS` are set by the last row.

**Comment by Hironsan** [comment]
Thanks!
